[package]
name = "day7"
version = "0.1.0"
authors = ["aimeedeer <aimeez@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
regex = "1.4.3"
lazy_static = "1.4.0"
